name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    tags: ["**"]
  workflow_dispatch:

jobs:
  build_and_push:
    environment: prod
    env:
      GAR_LOCATION: us-central1
      PROJECT_ID: prod-f0181862
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
      
      - name: Record timestamp
        run: |
          bin/build-package-start
      
      - name: Build the prometheus-dirsize-exporter image
        run: |
          bin/build-image prometheus-dirsize-exporter
      
      - name: Push to GCP Artifact Registry
        if: github.event_name != 'pull_request'
        env:
          GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
        run: |
          bin/build-docker-push prometheus_dirsize_exporter